package com.modelo;
// Generated 22/05/2020 9:15:32 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private int ide;
     private Nivel nivel;
     private String cedula;
     private String nombres;
     private String apellidos;
     private String direccion;
     private int edad;
     private Date fechan;
     private String cedular;
     private String nombresr;
     private String apellidosr;
     private String celular;

    public Alumno() {
    }

	
    public Alumno(int ide, String cedula, String nombres, String apellidos, String direccion, int edad, Date fechan, String cedular, String nombresr, String apellidosr, String celular) {
        this.ide = ide;
        this.cedula = cedula;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.direccion = direccion;
        this.edad = edad;
        this.fechan = fechan;
        this.cedular = cedular;
        this.nombresr = nombresr;
        this.apellidosr = apellidosr;
        this.celular = celular;
    }
    public Alumno(int ide, Nivel nivel, String cedula, String nombres, String apellidos, String direccion, int edad, Date fechan, String cedular, String nombresr, String apellidosr, String celular) {
       this.ide = ide;
       this.nivel = nivel;
       this.cedula = cedula;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.edad = edad;
       this.fechan = fechan;
       this.cedular = cedular;
       this.nombresr = nombresr;
       this.apellidosr = apellidosr;
       this.celular = celular;
    }

    public Alumno(Nivel nivel, String cedula, String nombres, String apellidos, String direccion, int edad, Date fechan, String cedular, String nombresr, String apellidosr, String celular) {
        this.nivel = nivel;
        this.cedula = cedula;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.direccion = direccion;
        this.edad = edad;
        this.fechan = fechan;
        this.cedular = cedular;
        this.nombresr = nombresr;
        this.apellidosr = apellidosr;
        this.celular = celular;
    }

    public Alumno(String cedula, String nombres, String apellidos, String direccion, int edad, Date fechan, String cedular, String nombresr, String apellidosr, String celular) {
        this.cedula = cedula;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.direccion = direccion;
        this.edad = edad;
        this.fechan = fechan;
        this.cedular = cedular;
        this.nombresr = nombresr;
        this.apellidosr = apellidosr;
        this.celular = celular;
    }
    
    
   
    public int getIde() {
        return this.ide;
    }
    
    public void setIde(int ide) {
        this.ide = ide;
    }
    public Nivel getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Nivel nivel) {
        this.nivel = nivel;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public Date getFechan() {
        return this.fechan;
    }
    
    public void setFechan(Date fechan) {
        this.fechan = fechan;
    }
    public String getCedular() {
        return this.cedular;
    }
    
    public void setCedular(String cedular) {
        this.cedular = cedular;
    }
    public String getNombresr() {
        return this.nombresr;
    }
    
    public void setNombresr(String nombresr) {
        this.nombresr = nombresr;
    }
    public String getApellidosr() {
        return this.apellidosr;
    }
    
    public void setApellidosr(String apellidosr) {
        this.apellidosr = apellidosr;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }




}


